# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-06 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('blog', '0002_blog_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='role',
        ),
        migrations.AddField(
            model_name='blog',
            name='auth_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
