# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-12 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181212_0703'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Published_blog',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='published',
        ),
        migrations.AddField(
            model_name='blog',
            name='Published_status',
            field=models.CharField(blank=True, choices=[('n', 'NotPublised'), ('p', 'Published')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
